// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJooCLddwuMJyTbrmeujfIL9WisArYdAU',
    appId: '1:313391745502:web:a6ccb757bc18b3ae27b54f',
    messagingSenderId: '313391745502',
    projectId: 'messagex-7ad9f',
    authDomain: 'messagex-7ad9f.firebaseapp.com',
    storageBucket: 'messagex-7ad9f.firebasestorage.app',
    measurementId: 'G-64S33RTF1X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzo1iDPy7LLCUzK7U8Mq_dyXgNVDB8B58',
    appId: '1:313391745502:android:de1c3a08bfa5c63b27b54f',
    messagingSenderId: '313391745502',
    projectId: 'messagex-7ad9f',
    storageBucket: 'messagex-7ad9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTtijXaoV9PdjVlhI3n5LFBAfUm6IiKzo',
    appId: '1:313391745502:ios:87604670c0125dc627b54f',
    messagingSenderId: '313391745502',
    projectId: 'messagex-7ad9f',
    storageBucket: 'messagex-7ad9f.firebasestorage.app',
    iosBundleId: 'com.example.messagex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTtijXaoV9PdjVlhI3n5LFBAfUm6IiKzo',
    appId: '1:313391745502:ios:87604670c0125dc627b54f',
    messagingSenderId: '313391745502',
    projectId: 'messagex-7ad9f',
    storageBucket: 'messagex-7ad9f.firebasestorage.app',
    iosBundleId: 'com.example.messagex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJooCLddwuMJyTbrmeujfIL9WisArYdAU',
    appId: '1:313391745502:web:0ea6bd49519aa47927b54f',
    messagingSenderId: '313391745502',
    projectId: 'messagex-7ad9f',
    authDomain: 'messagex-7ad9f.firebaseapp.com',
    storageBucket: 'messagex-7ad9f.firebasestorage.app',
    measurementId: 'G-77SPP8L678',
  );
}
